server:
  port: 6969
  
spring:
  datasource:
    username: root
    password: manager
    url: jdbc:mysql://localhost:3306/ihis
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update